services:

  api-python:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: api-produtos

    ports:
    - "8000:8000"

    environment:
      MONGO_URL: mongodb://admin:admin@mongodb:27017/loja_automotiva?authSource=admin
    
    depends_on:
      - mongodb

    restart: always

  mongodb:
    image: mongo:8.0

    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    ports:
      - "27017:27017"
    
    volumes:
      - mongodb_data:/data/db

    restart: always

volumes:
  mongodb_data: